apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-hpa
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85
